java_binary(
    name = "CampCleanup",
    srcs = ["CampCleanup.java"],
    resources = glob(["*.txt"]),
    deps = [
        "//src/main/java/aoccommon:aoccommon",
        "@google_bazel_common//third_party/java/guava",
    ],
)
